version: 2

jobs:
  Apollo Client:
    docker:
      - image: cimg/node:14.17.4

    steps:
      - checkout
      - run: cd final/client && npm ci
      - run: cd final/client && npm test
      - run: cd final/client && npx apollo client:check

      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            cd final/client && npx apollo client:push
          fi

  Apollo Server:
    docker:
      - image: cimg/node:14.17.4

    steps:
      - checkout
      - run: cd final/server && npm ci
      - run: cd final/server && npm test

      - run:
          name: Starting server
          command: cd final/server && npm run start:ci
          background: true

      - run: sleep 5
      - run: cd final/server && npx rover graph introspect http://localhost:4000 | npx rover graph check space-explorer  --schema -

      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            cd final/server && npx rover graph introspect http://localhost:4000 | npx rover graph publish space-explorer --schema -
          fi

workflows:
  version: 2
  Build and Test:
    jobs:
      - Apollo Client
      - Apollo Server
